anypoint:
  apiId: "0000000"
https:
  host: "0.0.0.0"
  port: "8082"
  keystore:
    path: "certificates/keystore.jks"
    password: "![D4+v1CUytkrdHeMLuFlD0w==]"
#---------------------------------------   
basicAuth:
  adminUser: "admin"
  adminPassword: "![72nmzOUYZqR2i2p0sKLJRQ==]" #admin
#--------------------------------------- 
# Monitoring configuration
#---------------------------------------
cloudhub:
  host: "anypoint.mulesoft.com"
  port: "443"
  user: "<<user-name>>"
  password: "<password>"
  environmentName: "Sandbox"
  organizationName: "<<org-name>>"
  region: "us-east-1" #Required for AnypointMQ stats