#%RAML 1.0 Library
usage: Health check resource for api
resourceTypes: 
  healthcheck:
    get:
      responses: 
        200:
          description: API is healthy and working normally
        500:
          description: There is an issue with the API or a downstream system
          body: 
            application/json:
              type: object
              properties: 
                error-code:
                  type: string
                  required: true
                message:
                  type: string
                  required: true
