#%RAML 1.0
version: v1
title: anypoint-statistics-api
baseUri: http://localhost:8081/v1
protocols: [HTTPS]
mediaType: [application/json]
uses:
  commonType: exchange_modules/0fbad185-3ef9-4dd7-ba7b-77729032c324/common-datatype/1.0.3/common-datatype.raml 
  healthCheckResource: exchange_modules/0fbad185-3ef9-4dd7-ba7b-77729032c324/health-check-resource/1.0.0/health-check-resource.raml
  
traits: 
  client-id-enforcment:
    headers: 
      client-id:
      client-secret:
securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication  
securedBy: [basic]   
/statistics:
  get:
    responses: 
      200:
        body:
          application/json:
/healthCheck:
  type: healthCheckResource.healthcheck
            